name: SmartLogic
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'README.md'
  - 'Guardfile'
markdown: kramdown
highlighter: null
sass:
  sass_dir: _sass
  style: :compressed
navigation:
- title: About
  url: /about.html
  subnavigation:
  - title: Four keys to building smarter software.
    url: /four-keys.html
    parent: /about.html
  - title: Who we work with.
    url: /who-we-work-with.html
    parent: /about.html
  - title: The Team.
    url: /team.html
    parent: /about.html
- title: Experience
  url: /experience.html
  subnavigation:
  - title: Case Studies
    url: /case-studies.html
    parent: /experience.html
  - title: Areas of Expertise
    url: /areas-of-expertise.html
    parent: /experience.html
  - title: Let's Work Together
    url: /lets-work-together.html
    parent: /experience.html
- title: Smart Thinking
  url: /smart-thinking.html
  subnavigation:
  - title: Community
    url: /community.html
    parent: /smart-thinking.html
- title: Get In Touch
  url: /get-in-touch.html
  subnavigation:
  - title: Work With Us
    url: /work-with-us.html
    parent: /get-in-touch.html
  - title: Our Office
    url: /office.html
    parent: /get-in-touch.html
  - title: Location
    url: /location.html
    parent: /get-in-touch.html
- title: What makes us different
  url: /what-makes-us-different.html
