name: SmartLogic
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'README.md'
  - 'Guardfile'
markdown: kramdown
highlighter: null
sass:
  sass_dir: _sass
  style: :compressed
navigation:
- title: About
  url: /about.html
- title: Experience
  url: /experience.html
- title: Smart Thinking
  url: /smart-thinking.html
- title: Get In Touch
  url: /get-in-touch.html
- title: What makes us different
  url: /what-makes-us-different.html
